name: Setup ngrok + RDP + Persistent Apps

on:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate cache key
        id: cache-key
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $key = "windows-fullcache-$date-${{ github.run_number }}"
          echo "cache-key=$key" >> $env:GITHUB_OUTPUT
          echo "restore-key=windows-fullcache-$date" >> $env:GITHUB_OUTPUT

      - name: Restore cached data
        uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: |
            C:\Windows\Temp\apps-cache
            C:\Windows\Temp\cache
            C:\Users\runneradmin\Documents
            C:\Users\runneradmin\Desktop
            C:\Users\runneradmin\Downloads
          key: ${{ steps.cache-key.outputs.cache-key }}
          restore-keys: |
            ${{ steps.cache-key.outputs.restore-key }}
            windows-fullcache-

      - name: Prepare cache directories
        run: |
          New-Item -Path "C:\Windows\Temp\apps-cache" -ItemType Directory -Force
          New-Item -Path "C:\Windows\Temp\cache" -ItemType Directory -Force

      - name: Install Chocolatey if missing
        run: |
          if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

      - name: Install apps (setup + portable)
        run: |
          $apps = @{
            "Chrome" = "https://dl.google.com/chrome/install/375.126/chrome_installer.exe"
            "Firefox" = "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US"
            "VSCode" = "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
            "NotepadPP" = "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.9/npp.8.6.9.Installer.exe"
            "7zip" = "https://www.7-zip.org/a/7z2301-x64.exe"
          }

          $cacheRoot = "C:\Windows\Temp\apps-cache"

          foreach ($app in $apps.Keys) {
              $installerUrl = $apps[$app]
              $appFolder = Join-Path $cacheRoot $app
              $installedFlag = Join-Path $appFolder "installed.flag"

              if (!(Test-Path $installedFlag)) {
                  New-Item -Path $appFolder -ItemType Directory -Force

                  $installerPath = Join-Path $env:TEMP "$app-installer.exe"
                  Invoke-WebRequest $installerUrl -OutFile $installerPath

                  # Run installer silently to custom folder
                  Start-Process -FilePath $installerPath -ArgumentList "/S /D=$appFolder" -Wait

                  # Mark as installed
                  New-Item -Path $installedFlag -ItemType File
                  Write-Host "✅ $app installed and cached"
              } else {
                  Write-Host "✅ $app already installed, using cache"
              }
          }

      - name: Add cached apps to PATH
        run: |
          $env:Path += ";C:\Windows\Temp\apps-cache\Chrome;C:\Windows\Temp\apps-cache\Firefox;C:\Windows\Temp\apps-cache\VSCode;C:\Windows\Temp\apps-cache\NotepadPP;C:\Windows\Temp\apps-cache\7zip"

      - name: Download & Setup ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop & set password
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $secPass = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $secPass

      - name: Start ngrok TCP tunnel
        run: Start-Process -FilePath .\ngrok.exe -ArgumentList "tcp 3389" -WindowStyle Hidden

      - name: Keep runner alive 6h + auto AppData cache + ngrok URL
        run: |
          function Save-All-AppData {
              Write-Host "💾 Saving all AppData folders..."
              $cacheRoot = "C:\Windows\Temp\cache\AppData"
              $localDest = Join-Path $cacheRoot "Local"
              $roamingDest = Join-Path $cacheRoot "Roaming"

              # Local AppData
              $localSource = "$env:USERPROFILE\AppData\Local"
              New-Item -Path $localDest -ItemType Directory -Force
              Get-ChildItem $localSource -Directory | ForEach-Object {
                  $name = $_.Name
                  if ($name -in @("Microsoft","Temp","Packages","ConnectedDevicesPlatform")) { return }
                  robocopy $_.FullName (Join-Path $localDest $name) /E /XJ /R:1 /W:1 /MT:8 | Out-Null
              }

              # Roaming AppData
              $roamingSource = "$env:USERPROFILE\AppData\Roaming"
              New-Item -Path $roamingDest -ItemType Directory -Force
              Get-ChildItem $roamingSource -Directory | ForEach-Object {
                  $name = $_.Name
                  if ($name -in @("Microsoft","npm")) { return }
                  robocopy $_.FullName (Join-Path $roamingDest $name) /E /XJ /R:1 /W:1 /MT:8 | Out-Null
              }
              Write-Host "✅ All AppData cached"
          }

          function Save-Cache {
              Write-Host "💾 Saving full cache..."
              $folders = @(
                  "C:\Users\runneradmin\Documents",
                  "C:\Users\runneradmin\Desktop",
                  "C:\Users\runneradmin\Downloads",
                  "C:\Windows\Temp\apps-cache"
              )
              $cacheDir = "C:\Windows\Temp\cache"

              foreach ($f in $folders) {
                  if (Test-Path $f) {
                      robocopy $f "$cacheDir\$(Split-Path $f -Leaf)" /E /XJ /R:1 /W:1 /MT:8 | Out-Null
                  }
              }

              Save-All-AppData
              Write-Host "✅ Full cache saved"
          }

          for ($i = 0; $i -lt 72; $i++) {
              Write-Host "⏳ Runner alive: iteration $($i+1)/72 ($(($i*5)) minutes elapsed)"

              if ($i % 6 -eq 0) { Save-Cache }

              try {
                  $resp = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
                  $tcpAddr = ($resp.tunnels | Where-Object { $_.proto -eq "tcp" }).public_url
                  if ($tcpAddr) { Write-Host "🌐 Ngrok RDP URL: $tcpAddr (user: runneradmin / pass: P@ssw0rd!)" }
              } catch { Write-Host "⚠️ Ngrok API not responding yet..." }

              Start-Sleep -Seconds 300
          }

          # Final cache save
          Save-Cache

      - name: Save final cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            C:\Windows\Temp\apps-cache
            C:\Windows\Temp\cache
            C:\Users\runneradmin\Documents
            C:\Users\runneradmin\Desktop
            C:\Users\runneradmin\Downloads
          key: ${{ steps.cache-key.outputs.cache-key }}
